const { app } = require("./index.js");
const { getLogin } = require("d:/Node.js/Day10 task/controllers/getLogin");
const { postLogin } = require("d:/Node.js/Day10 task/controllers/postLogin");
const { home } = require("d:/Node.js/Day10 task/controllers/home");
const { getRegister } = require("d:/Node.js/Day10 task/controllers/getRegister");
const { postRegister } = require("d:/Node.js/Day10 task/controllers/postRegister");
const { logout } = require("d:/Node.js/Day10 task/controllers/logout");
const { getaddStudent } = require("./controllers/getAddStudent.js");
const { postaddStudent } = require("./controllers/postAddStudent.js");
const { getStudents } = require("d:/Node.js/Day10 task/controllers/getStudents");
const { getUsers } = require("d:/Node.js/Day10 task/controllers/getUsers");
const { deleteUser } = require("d:/Node.js/Day10 task/controllers/deleteUser");
const { getEditStudent } = require("d:/Node.js/Day10 task/controllers/getEditStudent");
const { postEditStudent } = require("d:/Node.js/Day10 task/controllers/postEditStudent");
const { deleteStudent } = require("d:/Node.js/Day10 task/controllers/deleteStudent");

app.get("/login", getLogin);
app.post("/login", postLogin);
app.get('/',home);
app.get('/register',getRegister);
app.post('/register',postRegister);
app.get('/logout',logout);
app.get('/add-student', getaddStudent);
app.post('/add-student', postaddStudent);
app.get('/students', getStudents);
app.get('/users', getUsers);
app.post('/deleteUser/:id',deleteUser);
app.get('/edit-student/:id', getEditStudent);
app.post('/edit-student/:id', postEditStudent);
app.post('/delete-student/:id', deleteStudent);